const dogsData = [
  {
    name: "Rex",
    avatar: "./images/monkey-img-1.webp",
    age: 1,
    bio: "Art. Literature. Natural wine. Yoga.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Bella",
    avatar: "./images/monkey-img-2.webp",
    age: 2,
    bio: "Yup, that's my owner. U can meet him if you want",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Polly",
    avatar: "./images/monkey-img-1.jpg",
    age: 3,
    bio: "How you doin?",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Arthur",
    avatar: "./images/monkey-img-2.jpg",
    age: 4,
    bio: "Art. Literature. Natural wine. Yoga.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Sally",
    avatar: "./images/monkey-img-3.jpg",
    age: 5,
    bio: "Yup, that's my owner. U can meet him if you want",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Teddy",
    avatar: "./images/monkey-img-4.jpg",
    age: 6,
    bio: "How you doin?",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Rex",
    avatar: "./images/monkey-img-5.jpg",
    age: 7,
    bio: "Art. Literature. Natural wine. Yoga.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Bella",
    avatar: "./images/monkey-img-6.jpg",
    age: 8,
    bio: "Yup, that's my owner. U can meet him if you want",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Rex",
    avatar: "./images/monkey-img-7.jpg",
    age: 10,
    bio: "Art. Literature. Natural wine. Yoga.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Bella",
    avatar: "./images/monkey-img-8.jpg",
    age: 11,
    bio: "Yup, that's my owner. U can meet him if you want",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Bruno",
    avatar: "./images/monkey-img-9.jpg",
    age: 12,
    bio: "How you doin?",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Rex",
    avatar: "./images/monkey-img-10.jpg",
    age: 13,
    bio: "Art. Literature. Natural wine. Yoga.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Bella",
    avatar: "./images/monkey-img-11.jpg",
    age: 14,
    bio: "Yup, that's my owner. U can meet him if you want",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Teddy",
    avatar: "./images/monkey-img-12.jpg",
    age: 15,
    bio: "How you doin?",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Bella",
    avatar: "./images/monkey-img-14.jpg",
    age: 17,
    bio: "Yup, that's my owner. U can meet him if you want",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Teddy",
    avatar: "./images/monkey-img-15.jpg",
    age: 18,
    bio: "How you doin?",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Rex",
    avatar: "./images/monkey-img-16.jpg",
    age: 19,
    bio: "Art. Literature. Natural wine. Yoga.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Teddy",
    avatar: "./images/monkey-img-18.jpg",
    age: 21,
    bio: "How you doin?",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
];
export default dogsData;
