const dogsData = [
  {
    name: "Rex",
    avatar: "./images/monkey-img-1.webp",
    age: 1,
    bio: "Loves bananas and playing with crisp packets",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Bella",
    avatar: "./images/monkey-img-2.webp",
    age: 6,
    bio: "Hey, I love hanging around",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Polly",
    avatar: "./images/monkey-img-3.jpg",
    age: 14,
    bio: "I know everything",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Sidney",
    avatar: "./images/monkey-img-4.jpg",
    age: 3,
    bio: "Inquisitive and can't wait to meet you",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Sally",
    avatar: "./images/monkey-img-5.jpg",
    age: 10,
    bio: "Likes to observe and can be shy",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Teddy",
    avatar: "./images/monkey-img-6.jpg",
    age: 13,
    bio: "Loves exploring beautiful places",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Charlie",
    avatar: "./images/monkey-img-7.jpg",
    age: 8,
    bio: "Loves lazing around and sleeping",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Spike",
    avatar: "./images/monkey-img-8.jpg",
    age: 15,
    bio: "Don't be so nosey",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Arnold",
    avatar: "./images/monkey-img-9.jpg",
    age: 18,
    bio: "Likes wine and good food",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Gertrude",
    avatar: "./images/monkey-img-10.jpg",
    age: 35,
    bio: "Works as a beautician",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Twiggy",
    avatar: "./images/monkey-img-11.jpg",
    age: 21,
    bio: "Likes partying and nights out",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "George",
    avatar: "./images/monkey-img-12.jpg",
    age: 24,
    bio: "Very creative and likes to paint",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Hannah",
    avatar: "./images/monkey-img-13.jpg",
    age: 26,
    bio: "Loves watching live sport",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Terrence",
    avatar: "./images/monkey-img-14.jpg",
    age: 27,
    bio: "Loves singing in the choir",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Robbie",
    avatar: "./images/monkey-img-15.jpg",
    age: 2,
    bio: "Everything is new to me but I love to play and explore the world",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Sheila",
    avatar: "./images/monkey-img-16.jpg",
    age: 15,
    bio: "Loves cooking and eating banana cake",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Screech",
    avatar: "./images/monkey-img-17.jpg",
    age: 7,
    bio: "A cheeky chappy who lives to have fun",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Arthur",
    avatar: "./images/monkey-img-18.jpg",
    age: 21,
    bio: "Likes gardening and fishing",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
];
export default dogsData;
